### ISSUE TITLE
Confused about compose permissions

### ISSUE THREAD

**Issue by sarpuser** [OpenMediaVault-Plugin-Developers/packages#23]
I am a little confused about how OMV-Compose handles directory mappings and permissions. I am sorry this is not the right place to ask this but I couldnt find anywhere else.

Here is my problem: I want to create separate users for each container and make it so that each container can only access their own files. I create shared folders at `docker/compose` (for the compose files) and `docker/volumes` for persistent data. These folders are owned by the default `root:users`.

```
sarp@omv:~ $ id pihole
uid=1003(pihole) gid=1003(pihole) groups=1003(pihole)
```

```yaml
---
# https://hub.docker.com/r/pihole/pihole
# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80/tcp"
    environment:
      TZ: 'America/New_York'
      PUID: '1003'
      PGID: '1003'
    # Volumes store your data between container upgrades
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/pihole/etc/pihole:/etc/pihole
      - CHANGE_TO_COMPOSE_DATA_PATH/pihole/etc/dnsmasq.d:/etc/dnsmasq.d
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    restart: unless-stopped
```

<img width="1131" alt="Screenshot 2024-12-19 at 13 29 12" src="https://github.com/user-attachments/assets/490acffd-9681-43eb-97bc-b29da7394bf5" />

### Here is what I am confused about

Looking at the directories created by the compose plugin, it looks like there is a mix of permissions. There are some folders owned by `root`, and some by `openmediavault-webgui:sarp`. Shoudn't the files be owned by `pihole:pihole`? How can pihole actually modify these files **(pihole is working correctly)**? Where on earth does `openmediavault-webgui:sarp` come from? Sarp is the user I created to be able to ssh in. The user openmediavault-webgui isnt in that group? What am I missing?

```
sarp@omv:~ $ ls -la /srv/dev-disk-by-uuid-0e3a3a91-c619-476a-97ef-5c45aa61223d/docker/volumes/pihole/etc/
total 16
drwxr-sr-x 4 root                  root 4096 Dec 19 13:24 .
drwxr-sr-x 3 root                  root 4096 Dec 19 13:24 ..
drwxr-sr-x 2 root                  root 4096 Dec 19 13:25 dnsmasq.d
drwxrwsr-x 3 openmediavault-webgui sarp 4096 Dec 19 13:25 pihole
sarp@omv:~ $ ls -la /srv/dev-disk-by-uuid-0e3a3a91-c619-476a-97ef-5c45aa61223d/docker/volumes/pihole/etc/pihole
total 9716
drwxrwsr-x 3 openmediavault-webgui sarp    4096 Dec 19 13:25 .
drwxr-sr-x 4 root                  root    4096 Dec 19 13:24 ..
-rw-r--r-- 1 root                  root       0 Dec 19 13:24 custom.list
-rw-r--r-- 1 openmediavault-webgui sarp       0 Dec 19 13:25 dhcp.leases
-rw-r--r-- 1 root                  root     651 Dec 19 13:24 dns-servers.conf
-rw-rw-r-- 1 openmediavault-webgui sarp 7200768 Dec 19 13:25 gravity.db
-rw-rw-r-- 1 openmediavault-webgui sarp   94208 Dec 19 13:25 gravity_old.db
-rw-r--r-- 1 root                  sarp 2521661 Dec 19 13:25 list.1.raw.githubusercontent.com.domains
-rw-r--r-- 1 root                  sarp      95 Dec 19 13:25 list.1.raw.githubusercontent.com.domains.sha1
-rw-r--r-- 1 root                  sarp      65 Dec 19 13:25 local.list
-rw-r--r-- 1 root                  root     289 Dec 19 13:24 logrotate
drwxr-sr-x 2 root                  sarp    4096 Dec 19 13:25 migration_backup
-rw-rw-r-- 1 openmediavault-webgui root     157 Dec 19 13:25 pihole-FTL.conf
-rw-rw-r-- 1 openmediavault-webgui sarp   81920 Dec 19 13:25 pihole-FTL.db
-rw-r--r-- 1 root                  root     209 Dec 19 13:25 setupVars.conf
-rw-r--r-- 1 root                  root      27 Dec 19 13:24 setupVars.conf.update.bak
-rw-r--r-- 1 root                  root     382 Dec 19 13:25 versions
```
